### PR TITLE
Failing to load images doesn't break the whole site anymore.

### LINKED ISSUE #4: Improve error resistance

### PR DESCRIPTION
**Pull request by hkurhinen**
fixes #4

### CODE REVIEW

File: modules/news/index.js [hunk 1]
```diff
@@ -55,44 +57,44 @@
...
+              callback();
+            }).catch((imageError) => {
+              console.error('Error loading news image', imageError);
+              callback();
             });
-        })
-          .catch(listErr => {
-            reject(listErr);
+
+          }, (err) => {
```
Comment (anttileppa) [inline modules/news/index.js]: log this error

Comment (hkurhinen) [inline modules/news/index.js]: will always be null, probably should delete whole err parameter from last callback
